# Generated by Django 3.0 on 2020-12-28 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20201228_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, through='groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
